<!DOCTYPE html>
<html lang="en">
<head>
  <title>Job Posted Successfully</title>
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

  <meta http-equiv="X-UA-Compatible" content="IE=edge" />

</head>
<body>
<%
    Private Function BuildMailText(Name,Designation, Organization)
	    mailBodyText=""		 
		If RecipientName <> "" And Designation <>"" And Organization <>"" Then
            mailBodyText = mailBodyText & "<table width='800' marginwidth='0' marginheight='0' leftmargin='0' topmargin='0' style='background-color:#e0e0e0  font-family: Helvetica, Arial, Geneva, sans-serif margin:0 padding:0 min-width: 800px margin: 0 auto'"
            mailBodyText = mailBodyText & "    margin='0' border='0'>"
            mailBodyText = mailBodyText & "    <tr>"
            mailBodyText = mailBodyText & "      <td>"
            mailBodyText = mailBodyText & "        <!-- Start Background -->"
            mailBodyText = mailBodyText & "        <table width='780' cellpadding='0' cellspacing='0' border='0' bgcolor='#e0e0e0' style='margin: 0 auto'>"
            mailBodyText = mailBodyText & "          <tr>"
            mailBodyText = mailBodyText & "            <td width='780' valign='top' align='center'>"
            mailBodyText = mailBodyText & ""
            mailBodyText = mailBodyText & "              <!-- Start Wrapper -->"
            mailBodyText = mailBodyText & "              <table width='780' cellpadding='0' cellspacing='0' border='0' style=''>"
            mailBodyText = mailBodyText & "                <tr>"
            mailBodyText = mailBodyText & "                  <td height='10' style='font-size:10px line-height:10px'></td>"
            mailBodyText = mailBodyText & "                  <!-- Spacer -->"
            mailBodyText = mailBodyText & "                </tr>"
            mailBodyText = mailBodyText & "              </table>"
            mailBodyText = mailBodyText & "              <table width='780' cellpadding='0' cellspacing='0' border='0' bgcolor='#FFFFFF' style='border-radius: 4px 4px 0px 0px background-color: #f3f3f3 border-bottom: 1px solid #e0e0e0'>"
            mailBodyText = mailBodyText & "                <tr>"
            mailBodyText = mailBodyText & "                  <td height='15' style='font-size:10px line-height:10px'> </td>"
            mailBodyText = mailBodyText & "                  <!-- Spacer -->"
            mailBodyText = mailBodyText & "                </tr>"
            mailBodyText = mailBodyText & "                <tr>"
            mailBodyText = mailBodyText & "                  <td align='left'>"
            mailBodyText = mailBodyText & "                    <!-- Start Container -->"
            mailBodyText = mailBodyText & "                    <table width='100%' cellpadding='0' cellspacing='0' border='0' class='container'>"
            mailBodyText = mailBodyText & "                      <tr>"
            mailBodyText = mailBodyText & "                        <td width='300'>"
            mailBodyText = mailBodyText & "                          <table width='300'>"
            mailBodyText = mailBodyText & "                            <tr>"
            mailBodyText = mailBodyText & "                              <td width='20'></td>"
            mailBodyText = mailBodyText & "                              <td style='font-family: Tahoma, Geneva, sans-serif font-size:12px line-height:18px'"
            mailBodyText = mailBodyText & "                                align='left'>"
            mailBodyText = mailBodyText & "                                <img src='logo.png' width='124' height='30' style='margin:0 padding:0 border:none display:block'"
            mailBodyText = mailBodyText & "                                  border='0' class='centerClass' alt='Bdjobs.com' />"
            mailBodyText = mailBodyText & "                              </td>"
            mailBodyText = mailBodyText & "                            </tr>"
            mailBodyText = mailBodyText & "                          </table>"
            mailBodyText = mailBodyText & "                        </td>"
            mailBodyText = mailBodyText & "                        <td width='385'></td>"
            mailBodyText = mailBodyText & "                        <td>"
            mailBodyText = mailBodyText & "                          <table width='75'>"
            mailBodyText = mailBodyText & "                            <tr>"
            mailBodyText = mailBodyText & "                              <td width='10'>"
            mailBodyText = mailBodyText & "                                <a href='https://www.facebook.com/mybdjobs/' target='_blank' style='text-decoration: none'>"
            mailBodyText = mailBodyText & "                                  <img src='fb.png' alt='facebook' width='30' height='30'>"
            mailBodyText = mailBodyText & "                                </a>"
            mailBodyText = mailBodyText & "                              </td>"
            mailBodyText = mailBodyText & "                              <td width='10'>"
            mailBodyText = mailBodyText & "                                <a href='http://youtube.com/mybdjobs/' style='text-decoration: none' target='_blank'>"
            mailBodyText = mailBodyText & "                                  <img src='youtube.png' alt='twitter' width='30' height='30'>"
            mailBodyText = mailBodyText & "                                </a>"
            mailBodyText = mailBodyText & "                              </td>"
            mailBodyText = mailBodyText & "                            </tr>"
            mailBodyText = mailBodyText & "                          </table>"
            mailBodyText = mailBodyText & "                        </td>"
            mailBodyText = mailBodyText & "                      </tr>"
            mailBodyText = mailBodyText & "                    </table>"
            mailBodyText = mailBodyText & "                  </td>"
            mailBodyText = mailBodyText & "                </tr>"
            mailBodyText = mailBodyText & "                <tr>"
            mailBodyText = mailBodyText & "                  <td height='15' style='font-size:10px line-height:10px'> </td>"
            mailBodyText = mailBodyText & "                  <!-- Spacer -->"
            mailBodyText = mailBodyText & "                </tr>"
            mailBodyText = mailBodyText & "              </table>"
            mailBodyText = mailBodyText & "              <table width='780' cellpadding='0' cellspacing='0' border='0' bgcolor='#fff' style='background-color: #fff'>"
            mailBodyText = mailBodyText & "                <tr>"
            mailBodyText = mailBodyText & "                  <td align='center'>"
            mailBodyText = mailBodyText & "                    <table width='730' align='center' cellpadding='0' cellspacing='0' border='0'>"
            mailBodyText = mailBodyText & "                      <tr>"
            mailBodyText = mailBodyText & "                        <td height='30'></td>"
            mailBodyText = mailBodyText & "                      </tr>"
            mailBodyText = mailBodyText & "                      <tr>"
            mailBodyText = mailBodyText & "                        <td height='15'></td>"
            mailBodyText = mailBodyText & "                      </tr>"
            mailBodyText = mailBodyText & "                      <tr>"
            mailBodyText = mailBodyText & "                        <td style='color: #212121 font-size: 16px line-height: 24px font-family: Helvetica,Arial, Geneva, sans-serif'>"
            mailBodyText = mailBodyText & "                          Hi <strong><%=Name%></strong>,"
            mailBodyText = mailBodyText & "                          </br>"
            mailBodyText = mailBodyText & "                          You have been invited to an interview from <strong><%=Organization%></strong> for the position"
            mailBodyText = mailBodyText & "                          of"
            mailBodyText = mailBodyText & "                          <strong><%=Designation%></strong>."
            mailBodyText = mailBodyText & "                          </br>"
            mailBodyText = mailBodyText & "                          To view details information and give your consent regarding presence in the interview, please"
            mailBodyText = mailBodyText & "                          login to mybdjobs from web or app."
            mailBodyText = mailBodyText & "                          </br>"
            mailBodyText = mailBodyText & "                          </br>"
            mailBodyText = mailBodyText & "                        </td>"
            mailBodyText = mailBodyText & "                      </tr>"
            mailBodyText = mailBodyText & "                      <tr>"
            mailBodyText = mailBodyText & "                        <td width='100%' align='center' style='width: 100%!important min-width 100%'>"
            mailBodyText = mailBodyText & "                          <table width='320' cellpadding='0' cellspacing='0' align='center' border='0' style='border-radius: 4px'>"
            mailBodyText = mailBodyText & "                            <tbody>"
            mailBodyText = mailBodyText & "                              <tr>"
            mailBodyText = mailBodyText & "                                <td width='75' height='42' bgcolor='#0fa935' align='center' valign='middle' style='border-radius: 40px font-family: Arial, Helvetica, sans-serif font-size: 16px background-color: #0fa935 color: #ffffff line-height:20px'"
            mailBodyText = mailBodyText & "                                  align='center'>"
            mailBodyText = mailBodyText & "                                  <table align='center'>"
            mailBodyText = mailBodyText & "                                    <tbody>"
            mailBodyText = mailBodyText & "                                      <tr>"
            mailBodyText = mailBodyText & "                                        <td width='130'>"
            mailBodyText = mailBodyText & "                                          <a href='http://corporate3.bdjobs.com/default.asp' target='_blank' alias=''"
            mailBodyText = mailBodyText & "                                            style='font-family: Helvetica, Arial,Geneva, sans-serif text-decoration: none color: #ffffff font-weight:bold font-size: 16px display: block'>"
            mailBodyText = mailBodyText & "                                            Mybdjobs panel"
            mailBodyText = mailBodyText & "                                          </a>"
            mailBodyText = mailBodyText & "                                        </td>"
            mailBodyText = mailBodyText & "                                        <td width='10'>"
            mailBodyText = mailBodyText & "                                          <img src='arrow.gif' alt='angle' width='6' height='10'>"
            mailBodyText = mailBodyText & "                                        </td>"
            mailBodyText = mailBodyText & "                                      </tr>"
            mailBodyText = mailBodyText & "                                    </tbody>"
            mailBodyText = mailBodyText & "                                  </table>"
            mailBodyText = mailBodyText & "                                </td>"
            mailBodyText = mailBodyText & "                                <td width='10'></td>"
            mailBodyText = mailBodyText & "                                <td width='15' height='42' bgcolor='#0fa935' align='center' valign='middle' style='border-radius: 40px font-family: Arial, Helvetica, sans-serif font-size: 16px background-color: #0fa935 color: #ffffff line-height:20px'"
            mailBodyText = mailBodyText & "                                  align='center'>"
            mailBodyText = mailBodyText & "                                  <table align='center'>"
            mailBodyText = mailBodyText & "                                    <tbody>"
            mailBodyText = mailBodyText & "                                      <tr>"
            mailBodyText = mailBodyText & "                                        <td width='35'>"
            mailBodyText = mailBodyText & "                                          <a href='http://corporate3.bdjobs.com/default.asp' target='_blank' alias=''"
            mailBodyText = mailBodyText & "                                            style='font-family: Helvetica, Arial,Geneva, sans-serif text-decoration: none color: #ffffff font-weight:bold font-size: 16px display: block'>"
            mailBodyText = mailBodyText & "                                            App"
            mailBodyText = mailBodyText & "                                          </a>"
            mailBodyText = mailBodyText & "                                        </td>"
            mailBodyText = mailBodyText & "                                        <td width='10'>"
            mailBodyText = mailBodyText & "                                          <img src='arrow.gif' alt='angle' width='6' height='10'>"
            mailBodyText = mailBodyText & "                                        </td>"
            mailBodyText = mailBodyText & "                                      </tr>"
            mailBodyText = mailBodyText & "                                    </tbody>"
            mailBodyText = mailBodyText & "                                  </table>"
            mailBodyText = mailBodyText & "                                </td>"
            mailBodyText = mailBodyText & "                              </tr>"
            mailBodyText = mailBodyText & "                            </tbody>"
            mailBodyText = mailBodyText & "                          </table>"
            mailBodyText = mailBodyText & "                        </td>"
            mailBodyText = mailBodyText & "                      </tr>"
            mailBodyText = mailBodyText & "                      <tr>"
            mailBodyText = mailBodyText & "                        <td>"
            mailBodyText = mailBodyText & "                          </br>"
            mailBodyText = mailBodyText & "                          </br>"
            mailBodyText = mailBodyText & "                          Thanks"
            mailBodyText = mailBodyText & "                          </br>"
            mailBodyText = mailBodyText & "                          Bdjobs.com"
            mailBodyText = mailBodyText & "                        </td>"
            mailBodyText = mailBodyText & "                      </tr>"
            mailBodyText = mailBodyText & "                      <tr>"
            mailBodyText = mailBodyText & "                        <td height='20'></td>"
            mailBodyText = mailBodyText & "                      </tr>"
            mailBodyText = mailBodyText & "                      <tr>"
            mailBodyText = mailBodyText & "                        <td height='20'></td>"
            mailBodyText = mailBodyText & "                      </tr>"
            mailBodyText = mailBodyText & "                    </table>"
            mailBodyText = mailBodyText & "                  </td>"
            mailBodyText = mailBodyText & "                </tr>"
            mailBodyText = mailBodyText & "              </table>"
            mailBodyText = mailBodyText & "              <table width='780' cellpadding='0' cellspacing='0' border='0' bgcolor='#263238' style='border-radius: 0px 0px 4px 4px background-color: #263238'>"
            mailBodyText = mailBodyText & "                <tr>"
            mailBodyText = mailBodyText & "                  <td width='30'></td>"
            mailBodyText = mailBodyText & "                  <td align='center'>"
            mailBodyText = mailBodyText & "                    <table style='text-align: center' class='container'>"
            mailBodyText = mailBodyText & "                      <tr>"
            mailBodyText = mailBodyText & "                        <td height='30'></td>"
            mailBodyText = mailBodyText & "                      </tr>"
            mailBodyText = mailBodyText & "                      <tr>"
            mailBodyText = mailBodyText & "                        <td align='center' style='color: #fff; font-size: 14px; font-weight: bold; font-family: Tahoma, Geneva, sans-serif line-height: 20px'>"
            mailBodyText = mailBodyText & "                          Need further assistance?"
            mailBodyText = mailBodyText & "                          <br>"
            mailBodyText = mailBodyText & "                          Contact with our Customer relation Manager."
            mailBodyText = mailBodyText & "                        </td>"
            mailBodyText = mailBodyText & "                      </tr>"
            mailBodyText = mailBodyText & "                      <tr>"
            mailBodyText = mailBodyText & "                        <td height='5'></td>"
            mailBodyText = mailBodyText & "                      </tr>"
            mailBodyText = mailBodyText & "                      <tr>"
            mailBodyText = mailBodyText & "                        <td align='center' style='color: #fff; font-size: 12px; font-family: Tahoma, Geneva, sans-serif'>"
            mailBodyText = mailBodyText & "                          <i>Customer experience center open: <b>Saturday</b> to <b>Thursday</b> (10.00 AM to 6.00 PM)</i>"
            mailBodyText = mailBodyText & "                        </td>"
            mailBodyText = mailBodyText & "                      </tr>"
            mailBodyText = mailBodyText & "                      <tr>"
            mailBodyText = mailBodyText & "                        <td height='5'></td>"
            mailBodyText = mailBodyText & "                      </tr>"
            mailBodyText = mailBodyText & "                      <tr>"
            mailBodyText = mailBodyText & "                        <td style='color: #96999b; font-size: 12px; line-height: 20px; font-family: Tahoma, Geneva, sans-serif'>"
            mailBodyText = mailBodyText & "                          Bdjobs.com Limited • BDBL Bhaban (8th Floor-West), 12, Kazi Nazrul Islam Avenue, Dhaka 1215"
            mailBodyText = mailBodyText & "                        </td>"
            mailBodyText = mailBodyText & "                      </tr>"
            mailBodyText = mailBodyText & "                      <tr>"
            mailBodyText = mailBodyText & "                        <td align='center'>"
            mailBodyText = mailBodyText & "                          <table>"
            mailBodyText = mailBodyText & "                            <tbody>"
            mailBodyText = mailBodyText & "                              <tr>"
            mailBodyText = mailBodyText & "                                <td width='12'>"
            mailBodyText = mailBodyText & "                                  <img src='phone.png' alt='phone' width='28' height='28'>"
            mailBodyText = mailBodyText & "                                </td>"
            mailBodyText = mailBodyText & "                                <td style='font-size: 14px font-weight: bold font-family: Tahoma, Geneva, sans-serif'>"
            mailBodyText = mailBodyText & "                                  <a style='color: #ffd600'>09612-444888</a>"
            mailBodyText = mailBodyText & "                                </td>"
            mailBodyText = mailBodyText & "                              </tr>"
            mailBodyText = mailBodyText & "                            </tbody>"
            mailBodyText = mailBodyText & "                          </table>"
            mailBodyText = mailBodyText & "                        </td>"
            mailBodyText = mailBodyText & "                      </tr>"
            mailBodyText = mailBodyText & "                      <tr>"
            mailBodyText = mailBodyText & "                        <td height='10'></td>"
            mailBodyText = mailBodyText & "                      </tr>"
            mailBodyText = mailBodyText & "                      <tr>"
            mailBodyText = mailBodyText & "                        <td height='10'></td>"
            mailBodyText = mailBodyText & "                      </tr>"
            mailBodyText = mailBodyText & "                    </table>"
            mailBodyText = mailBodyText & "                  </td>"
            mailBodyText = mailBodyText & "                  <td width='30'></td>"
            mailBodyText = mailBodyText & "                </tr>"
            mailBodyText = mailBodyText & "              </table>"
            mailBodyText = mailBodyText & "            </td>"
            mailBodyText = mailBodyText & "          </tr>"
            mailBodyText = mailBodyText & "          <tr>"
            mailBodyText = mailBodyText & "            <td height='10'></td>"
            mailBodyText = mailBodyText & "          </tr>"
            mailBodyText = mailBodyText & "        </table>"
            mailBodyText = mailBodyText & "      </td>"
            mailBodyText = mailBodyText & "    </tr>"
            mailBodyText = mailBodyText & "  </table>"
		End If
		BuildMailText = mailBodyText
	End Function
%>
 
</body>
</html>